// <auto-generated />
namespace carrentalservice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class New : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(New));
        
        string IMigrationMetadata.Id
        {
            get { return "202108052135133_New"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
